const GET_DATA = 'GET_DATA';
const SET_DATA = 'SET_DATA';
const GET_S2ID_LIST = 'GET_S2ID_LIST';
const SET_S2ID_LIST = 'SET_S2ID_LIST';
const GET_COMPANY_LIST = 'GET_COMPANY_LIST';
const SET_COMPANY_LIST = 'SET_COMPANY_LIST';

export {  //eslint-disable-line
  GET_DATA,
  SET_DATA,
  GET_S2ID_LIST,
  SET_S2ID_LIST,
  GET_COMPANY_LIST,
  SET_COMPANY_LIST
};
